import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className='font-mono text-6xl font-semibold text-center'>
          Spacestagram comming soon...{' '}
          <a href='https://www.alexmaldonado.dev/' className='text-blue-500'>
            My WebSite
          </a>
        </h1>
      </main>

      <Footer />
    </div>
  );
}
