import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import Card from '../components/Card';
import Posts from '../components/Posts';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spacestagram</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Posts />
      <Footer />
    </div>
  );
}
